/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.bonsai.simulatorapi.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Event asking to unregister/delete simulatorSession.
 * You can create a new session, if you want to continue training with this
 * simulator.
 */
public class Unregister {
    /**
     * Possible values include: 'Unspecified', 'Finished', 'Error', 'NotFound'.
     */
    @JsonProperty(value = "reason")
    private UnregisterReason reason;

    /**
     * Detail message for unregister event.
     */
    @JsonProperty(value = "details")
    private String details;

    /**
     * Get possible values include: 'Unspecified', 'Finished', 'Error', 'NotFound'.
     *
     * @return the reason value
     */
    public UnregisterReason reason() {
        return this.reason;
    }

    /**
     * Set possible values include: 'Unspecified', 'Finished', 'Error', 'NotFound'.
     *
     * @param reason the reason value to set
     * @return the Unregister object itself.
     */
    public Unregister withReason(UnregisterReason reason) {
        this.reason = reason;
        return this;
    }

    /**
     * Get detail message for unregister event.
     *
     * @return the details value
     */
    public String details() {
        return this.details;
    }

    /**
     * Set detail message for unregister event.
     *
     * @param details the details value to set
     * @return the Unregister object itself.
     */
    public Unregister withDetails(String details) {
        this.details = details;
        return this;
    }

}
