// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Bonsai.SimulatorApi.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for SimulatorContextTypesDeploymentMode.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum SimulatorContextTypesDeploymentMode
    {
        [EnumMember(Value = "Unspecified")]
        Unspecified,
        [EnumMember(Value = "Hosted")]
        Hosted,
        [EnumMember(Value = "Testing")]
        Testing
    }
    internal static class SimulatorContextTypesDeploymentModeEnumExtension
    {
        internal static string ToSerializedValue(this SimulatorContextTypesDeploymentMode? value)
        {
            return value == null ? null : ((SimulatorContextTypesDeploymentMode)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this SimulatorContextTypesDeploymentMode value)
        {
            switch( value )
            {
                case SimulatorContextTypesDeploymentMode.Unspecified:
                    return "Unspecified";
                case SimulatorContextTypesDeploymentMode.Hosted:
                    return "Hosted";
                case SimulatorContextTypesDeploymentMode.Testing:
                    return "Testing";
            }
            return null;
        }

        internal static SimulatorContextTypesDeploymentMode? ParseSimulatorContextTypesDeploymentMode(this string value)
        {
            switch( value )
            {
                case "Unspecified":
                    return SimulatorContextTypesDeploymentMode.Unspecified;
                case "Hosted":
                    return SimulatorContextTypesDeploymentMode.Hosted;
                case "Testing":
                    return SimulatorContextTypesDeploymentMode.Testing;
            }
            return null;
        }
    }
}
