/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as Models from "./models";
import * as Mappers from "./models/mappers";
import * as operations from "./operations";
import { SimulatorAPIContext } from "./simulatorAPIContext";

class SimulatorAPI extends SimulatorAPIContext {
  // Operation groups
  session: operations.Session;

  /**
   * Initializes a new instance of the SimulatorAPI class.
   * @param [options] The parameter options
   */
  constructor(options?: Models.SimulatorAPIOptions) {
    super(options);
    this.session = new operations.Session(this);
  }
}

// Operation Specifications

export {
  SimulatorAPI,
  SimulatorAPIContext,
  Models as SimulatorAPIModels,
  Mappers as SimulatorAPIMappers
};
export * from "./operations";
