/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.bonsai.simulatorapi.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The EpisodeFinish model.
 */
public class EpisodeFinish {
    /**
     * The reason property.
     */
    @JsonProperty(value = "reason", required = true)
    private int reason;

    /**
     * Get the reason value.
     *
     * @return the reason value
     */
    public int reason() {
        return this.reason;
    }

    /**
     * Set the reason value.
     *
     * @param reason the reason value to set
     * @return the EpisodeFinish object itself.
     */
    public EpisodeFinish withReason(int reason) {
        this.reason = reason;
        return this;
    }

}
