/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.bonsai.simulatorapi.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The EpisodeFinish model.
 */
public class EpisodeFinish {
    /**
     * Possible values include: 'Invalid', 'Unspecified', 'LessonChanged',
     * 'Terminal', 'Interrupted'.
     */
    @JsonProperty(value = "reason")
    private EpisodeFinishTypesReason reason;

    /**
     * Get possible values include: 'Invalid', 'Unspecified', 'LessonChanged', 'Terminal', 'Interrupted'.
     *
     * @return the reason value
     */
    public EpisodeFinishTypesReason reason() {
        return this.reason;
    }

    /**
     * Set possible values include: 'Invalid', 'Unspecified', 'LessonChanged', 'Terminal', 'Interrupted'.
     *
     * @param reason the reason value to set
     * @return the EpisodeFinish object itself.
     */
    public EpisodeFinish withReason(EpisodeFinishTypesReason reason) {
        this.reason = reason;
        return this;
    }

}
