/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.bonsai.simulatorapi.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The ListValue model.
 */
public class ListValue {
    /**
     * The values property.
     */
    @JsonProperty(value = "values")
    private List<Value> values;

    /**
     * Get the values value.
     *
     * @return the values value
     */
    public List<Value> values() {
        return this.values;
    }

    /**
     * Set the values value.
     *
     * @param values the values value to set
     * @return the ListValue object itself.
     */
    public ListValue withValues(List<Value> values) {
        this.values = values;
        return this;
    }

}
