/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.bonsai.simulatorapi.models;

import java.util.Map;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The SimulatorInterface model.
 */
public class SimulatorInterface {
    /**
     * The name property.
     */
    @JsonProperty(value = "name")
    private String name;

    /**
     * The timeout property.
     */
    @JsonProperty(value = "timeout", required = true)
    private double timeout;

    /**
     * The capabilities property.
     */
    @JsonProperty(value = "capabilities")
    private Map<String, Object> capabilities;

    /**
     * The simulatorContext property.
     */
    @JsonProperty(value = "simulatorContext")
    private String simulatorContext;

    /**
     * The description property.
     */
    @JsonProperty(value = "description")
    private Map<String, Object> description;

    /**
     * Get the name value.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name value.
     *
     * @param name the name value to set
     * @return the SimulatorInterface object itself.
     */
    public SimulatorInterface withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get the timeout value.
     *
     * @return the timeout value
     */
    public double timeout() {
        return this.timeout;
    }

    /**
     * Set the timeout value.
     *
     * @param timeout the timeout value to set
     * @return the SimulatorInterface object itself.
     */
    public SimulatorInterface withTimeout(double timeout) {
        this.timeout = timeout;
        return this;
    }

    /**
     * Get the capabilities value.
     *
     * @return the capabilities value
     */
    public Map<String, Object> capabilities() {
        return this.capabilities;
    }

    /**
     * Set the capabilities value.
     *
     * @param capabilities the capabilities value to set
     * @return the SimulatorInterface object itself.
     */
    public SimulatorInterface withCapabilities(Map<String, Object> capabilities) {
        this.capabilities = capabilities;
        return this;
    }

    /**
     * Get the simulatorContext value.
     *
     * @return the simulatorContext value
     */
    public String simulatorContext() {
        return this.simulatorContext;
    }

    /**
     * Set the simulatorContext value.
     *
     * @param simulatorContext the simulatorContext value to set
     * @return the SimulatorInterface object itself.
     */
    public SimulatorInterface withSimulatorContext(String simulatorContext) {
        this.simulatorContext = simulatorContext;
        return this;
    }

    /**
     * Get the description value.
     *
     * @return the description value
     */
    public Map<String, Object> description() {
        return this.description;
    }

    /**
     * Set the description value.
     *
     * @param description the description value to set
     * @return the SimulatorInterface object itself.
     */
    public SimulatorInterface withDescription(Map<String, Object> description) {
        this.description = description;
        return this;
    }

}
