/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.bonsai.simulatorapi.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The Timestamp model.
 */
public class Timestamp {
    /**
     * The seconds property.
     */
    @JsonProperty(value = "seconds", required = true)
    private long seconds;

    /**
     * The nanos property.
     */
    @JsonProperty(value = "nanos", required = true)
    private int nanos;

    /**
     * Get the seconds value.
     *
     * @return the seconds value
     */
    public long seconds() {
        return this.seconds;
    }

    /**
     * Set the seconds value.
     *
     * @param seconds the seconds value to set
     * @return the Timestamp object itself.
     */
    public Timestamp withSeconds(long seconds) {
        this.seconds = seconds;
        return this;
    }

    /**
     * Get the nanos value.
     *
     * @return the nanos value
     */
    public int nanos() {
        return this.nanos;
    }

    /**
     * Set the nanos value.
     *
     * @param nanos the nanos value to set
     * @return the Timestamp object itself.
     */
    public Timestamp withNanos(int nanos) {
        this.nanos = nanos;
        return this;
    }

}
