/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.bonsai.simulatorapi.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The Unregister model.
 */
public class Unregister {
    /**
     * The reason property.
     */
    @JsonProperty(value = "reason", required = true)
    private int reason;

    /**
     * The details property.
     */
    @JsonProperty(value = "details")
    private String details;

    /**
     * Get the reason value.
     *
     * @return the reason value
     */
    public int reason() {
        return this.reason;
    }

    /**
     * Set the reason value.
     *
     * @param reason the reason value to set
     * @return the Unregister object itself.
     */
    public Unregister withReason(int reason) {
        this.reason = reason;
        return this;
    }

    /**
     * Get the details value.
     *
     * @return the details value
     */
    public String details() {
        return this.details;
    }

    /**
     * Set the details value.
     *
     * @param details the details value to set
     * @return the Unregister object itself.
     */
    public Unregister withDetails(String details) {
        this.details = details;
        return this;
    }

}
