# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class SimulatorState(Model):
    """SimulatorState.

    :param session_id:
    :type session_id: str
    :param sequence_id:
    :type sequence_id: int
    :param state:
    :type state: object
    :param halted:
    :type halted: bool
    :param error:
    :type error: str
    """

    _attribute_map = {
        'session_id': {'key': 'sessionId', 'type': 'str'},
        'sequence_id': {'key': 'sequenceId', 'type': 'int'},
        'state': {'key': 'state', 'type': 'object'},
        'halted': {'key': 'halted', 'type': 'bool'},
        'error': {'key': 'error', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(SimulatorState, self).__init__(**kwargs)
        self.session_id = kwargs.get('session_id', None)
        self.sequence_id = kwargs.get('sequence_id', None)
        self.state = kwargs.get('state', None)
        self.halted = kwargs.get('halted', None)
        self.error = kwargs.get('error', None)
