# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class SimulatorInterface(Model):
    """SimulatorInterface.

    :param name:
    :type name: str
    :param timeout:
    :type timeout: float
    :param capabilities:
    :type capabilities: object
    :param simulator_context:
    :type simulator_context: str
    :param description:
    :type description: object
    """

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'timeout': {'key': 'timeout', 'type': 'float'},
        'capabilities': {'key': 'capabilities', 'type': 'object'},
        'simulator_context': {'key': 'simulatorContext', 'type': 'str'},
        'description': {'key': 'description', 'type': 'object'},
    }

    def __init__(self, *, name: str=None, timeout: float=None, capabilities=None, simulator_context: str=None, description=None, **kwargs) -> None:
        super(SimulatorInterface, self).__init__(**kwargs)
        self.name = name
        self.timeout = timeout
        self.capabilities = capabilities
        self.simulator_context = simulator_context
        self.description = description
