# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class Unregister(Model):
    """Unregister.

    :param reason: Possible values include: 'Unspecified', 'Finished',
     'Error', 'NotFound'
    :type reason: str or ~bonsai.simulatorapi.models.UnregisterTypesReason
    :param details:
    :type details: str
    """

    _attribute_map = {
        'reason': {'key': 'reason', 'type': 'UnregisterTypesReason'},
        'details': {'key': 'details', 'type': 'str'},
    }

    def __init__(self, *, reason=None, details: str=None, **kwargs) -> None:
        super(Unregister, self).__init__(**kwargs)
        self.reason = reason
        self.details = details
