/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.bonsai.simulatorapi.implementation;

import microsoft.bonsai.simulatorapi.SimulatorAPI;
import microsoft.bonsai.simulatorapi.Gateways;
import microsoft.bonsai.simulatorapi.SimulatorNotifications;
import microsoft.bonsai.simulatorapi.Simulators;
import microsoft.bonsai.simulatorapi.SimulatorSessions;
import com.microsoft.rest.ServiceClient;
import com.microsoft.rest.RestClient;
import okhttp3.OkHttpClient;
import retrofit2.Retrofit;

/**
 * Initializes a new instance of the SimulatorAPI class.
 */
public class SimulatorAPIImpl extends ServiceClient implements SimulatorAPI {

    /**
     * The Gateways object to access its operations.
     */
    private Gateways gateways;

    /**
     * Gets the Gateways object to access its operations.
     * @return the Gateways object.
     */
    public Gateways gateways() {
        return this.gateways;
    }

    /**
     * The SimulatorNotifications object to access its operations.
     */
    private SimulatorNotifications simulatorNotifications;

    /**
     * Gets the SimulatorNotifications object to access its operations.
     * @return the SimulatorNotifications object.
     */
    public SimulatorNotifications simulatorNotifications() {
        return this.simulatorNotifications;
    }

    /**
     * The Simulators object to access its operations.
     */
    private Simulators simulators;

    /**
     * Gets the Simulators object to access its operations.
     * @return the Simulators object.
     */
    public Simulators simulators() {
        return this.simulators;
    }

    /**
     * The SimulatorSessions object to access its operations.
     */
    private SimulatorSessions simulatorSessions;

    /**
     * Gets the SimulatorSessions object to access its operations.
     * @return the SimulatorSessions object.
     */
    public SimulatorSessions simulatorSessions() {
        return this.simulatorSessions;
    }

    /**
     * Initializes an instance of SimulatorAPI client.
     */
    public SimulatorAPIImpl() {
        this("https://api.bons.ai");
    }

    /**
     * Initializes an instance of SimulatorAPI client.
     *
     * @param baseUrl the base URL of the host
     */
    public SimulatorAPIImpl(String baseUrl) {
        super(baseUrl);
        initialize();
    }

    /**
     * Initializes an instance of SimulatorAPI client.
     *
     * @param clientBuilder the builder for building an OkHttp client, bundled with user configurations
     * @param restBuilder the builder for building an Retrofit client, bundled with user configurations
     */
    public SimulatorAPIImpl(OkHttpClient.Builder clientBuilder, Retrofit.Builder restBuilder) {
        this("https://api.bons.ai", clientBuilder, restBuilder);
        initialize();
    }

    /**
     * Initializes an instance of SimulatorAPI client.
     *
     * @param baseUrl the base URL of the host
     * @param clientBuilder the builder for building an OkHttp client, bundled with user configurations
     * @param restBuilder the builder for building an Retrofit client, bundled with user configurations
     */
    public SimulatorAPIImpl(String baseUrl, OkHttpClient.Builder clientBuilder, Retrofit.Builder restBuilder) {
        super(baseUrl, clientBuilder, restBuilder);
        initialize();
    }

    /**
     * Initializes an instance of SimulatorAPI client.
     *
     * @param restClient the REST client containing pre-configured settings
     */
    public SimulatorAPIImpl(RestClient restClient) {
        super(restClient);
        initialize();
    }

    private void initialize() {
        this.gateways = new GatewaysImpl(retrofit(), this);
        this.simulatorNotifications = new SimulatorNotificationsImpl(retrofit(), this);
        this.simulators = new SimulatorsImpl(retrofit(), this);
        this.simulatorSessions = new SimulatorSessionsImpl(retrofit(), this);
    }
}
