// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Bonsai.SimulatorApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class EpisodeFinish
    {
        /// <summary>
        /// Initializes a new instance of the EpisodeFinish class.
        /// </summary>
        public EpisodeFinish()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the EpisodeFinish class.
        /// </summary>
        /// <param name="reason">Possible values include: 'Invalid',
        /// 'Unspecified', 'LessonChanged', 'Terminal', 'Interrupted'</param>
        public EpisodeFinish(EpisodeFinishTypesReason? reason = default(EpisodeFinishTypesReason?))
        {
            Reason = reason;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets possible values include: 'Invalid', 'Unspecified',
        /// 'LessonChanged', 'Terminal', 'Interrupted'
        /// </summary>
        [JsonProperty(PropertyName = "reason")]
        public EpisodeFinishTypesReason? Reason { get; set; }

    }
}
