// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Bonsai.SimulatorApi.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for EpisodeFinishTypesReason.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum EpisodeFinishTypesReason
    {
        [EnumMember(Value = "Invalid")]
        Invalid,
        [EnumMember(Value = "Unspecified")]
        Unspecified,
        [EnumMember(Value = "LessonChanged")]
        LessonChanged,
        [EnumMember(Value = "Terminal")]
        Terminal,
        [EnumMember(Value = "Interrupted")]
        Interrupted
    }
    internal static class EpisodeFinishTypesReasonEnumExtension
    {
        internal static string ToSerializedValue(this EpisodeFinishTypesReason? value)
        {
            return value == null ? null : ((EpisodeFinishTypesReason)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this EpisodeFinishTypesReason value)
        {
            switch( value )
            {
                case EpisodeFinishTypesReason.Invalid:
                    return "Invalid";
                case EpisodeFinishTypesReason.Unspecified:
                    return "Unspecified";
                case EpisodeFinishTypesReason.LessonChanged:
                    return "LessonChanged";
                case EpisodeFinishTypesReason.Terminal:
                    return "Terminal";
                case EpisodeFinishTypesReason.Interrupted:
                    return "Interrupted";
            }
            return null;
        }

        internal static EpisodeFinishTypesReason? ParseEpisodeFinishTypesReason(this string value)
        {
            switch( value )
            {
                case "Invalid":
                    return EpisodeFinishTypesReason.Invalid;
                case "Unspecified":
                    return EpisodeFinishTypesReason.Unspecified;
                case "LessonChanged":
                    return EpisodeFinishTypesReason.LessonChanged;
                case "Terminal":
                    return EpisodeFinishTypesReason.Terminal;
                case "Interrupted":
                    return EpisodeFinishTypesReason.Interrupted;
            }
            return null;
        }
    }
}
