// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Bonsai.SimulatorAPI.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PurposeTarget
    {
        /// <summary>
        /// Initializes a new instance of the PurposeTarget class.
        /// </summary>
        public PurposeTarget()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PurposeTarget class.
        /// </summary>
        public PurposeTarget(int brainVersion, string workspaceName = default(string), string brainName = default(string), string conceptName = default(string))
        {
            WorkspaceName = workspaceName;
            BrainName = brainName;
            BrainVersion = brainVersion;
            ConceptName = conceptName;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "workspaceName")]
        public string WorkspaceName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "brainName")]
        public string BrainName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "brainVersion")]
        public int BrainVersion { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "conceptName")]
        public string ConceptName { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
