// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Bonsai.SimulatorAPI.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SimulatorSession
    {
        /// <summary>
        /// Initializes a new instance of the SimulatorSession class.
        /// </summary>
        public SimulatorSession()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SimulatorSession class.
        /// </summary>
        public SimulatorSession(int sessionStatus, double iterationRate, string sessionId = default(string), SimulatorSessionProgress sessionProgress = default(SimulatorSessionProgress), SimulatorInterface interfaceProperty = default(SimulatorInterface), SimulatorContext simulatorContext = default(SimulatorContext), Timestamp registrationTime = default(Timestamp), Timestamp lastSeenTime = default(Timestamp), string details = default(string))
        {
            SessionId = sessionId;
            SessionStatus = sessionStatus;
            SessionProgress = sessionProgress;
            InterfaceProperty = interfaceProperty;
            SimulatorContext = simulatorContext;
            RegistrationTime = registrationTime;
            LastSeenTime = lastSeenTime;
            IterationRate = iterationRate;
            Details = details;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sessionId")]
        public string SessionId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sessionStatus")]
        public int SessionStatus { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sessionProgress")]
        public SimulatorSessionProgress SessionProgress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "interface")]
        public SimulatorInterface InterfaceProperty { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "simulatorContext")]
        public SimulatorContext SimulatorContext { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "registrationTime")]
        public Timestamp RegistrationTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lastSeenTime")]
        public Timestamp LastSeenTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "iterationRate")]
        public double IterationRate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "details")]
        public string Details { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (SessionProgress != null)
            {
                SessionProgress.Validate();
            }
            if (InterfaceProperty != null)
            {
                InterfaceProperty.Validate();
            }
            if (SimulatorContext != null)
            {
                SimulatorContext.Validate();
            }
            if (RegistrationTime != null)
            {
                RegistrationTime.Validate();
            }
            if (LastSeenTime != null)
            {
                LastSeenTime.Validate();
            }
        }
    }
}
