// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Bonsai.SimulatorAPI.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SimulatorSessionMilestone
    {
        /// <summary>
        /// Initializes a new instance of the SimulatorSessionMilestone class.
        /// </summary>
        public SimulatorSessionMilestone()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SimulatorSessionMilestone class.
        /// </summary>
        public SimulatorSessionMilestone(Timestamp firstTime = default(Timestamp))
        {
            FirstTime = firstTime;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "firstTime")]
        public Timestamp FirstTime { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (FirstTime != null)
            {
                FirstTime.Validate();
            }
        }
    }
}
