// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Bonsai.SimulatorApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Step
    {
        /// <summary>
        /// Initializes a new instance of the Step class.
        /// </summary>
        public Step()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Step class.
        /// </summary>
        public Step(object action = default(object))
        {
            Action = action;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "action")]
        public object Action { get; set; }

    }
}
