// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Bonsai.SimulatorAPI.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Timestamp
    {
        /// <summary>
        /// Initializes a new instance of the Timestamp class.
        /// </summary>
        public Timestamp()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Timestamp class.
        /// </summary>
        public Timestamp(long seconds, int nanos)
        {
            Seconds = seconds;
            Nanos = nanos;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "seconds")]
        public long Seconds { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "nanos")]
        public int Nanos { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
