// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Bonsai.SimulatorApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Unregister
    {
        /// <summary>
        /// Initializes a new instance of the Unregister class.
        /// </summary>
        public Unregister()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Unregister class.
        /// </summary>
        /// <param name="reason">Possible values include: 'Unspecified',
        /// 'Finished', 'Error', 'NotFound'</param>
        public Unregister(UnregisterTypesReason? reason = default(UnregisterTypesReason?), string details = default(string))
        {
            Reason = reason;
            Details = details;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets possible values include: 'Unspecified', 'Finished',
        /// 'Error', 'NotFound'
        /// </summary>
        [JsonProperty(PropertyName = "reason")]
        public UnregisterTypesReason? Reason { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "details")]
        public string Details { get; set; }

    }
}
