/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package bonsai.simulatorapi.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The EpisodeStart model.
 */
public class EpisodeStart {
    /**
     * The config property.
     */
    @JsonProperty(value = "config")
    private Object config;

    /**
     * Get the config value.
     *
     * @return the config value
     */
    public Object config() {
        return this.config;
    }

    /**
     * Set the config value.
     *
     * @param config the config value to set
     * @return the EpisodeStart object itself.
     */
    public EpisodeStart withConfig(Object config) {
        this.config = config;
        return this;
    }

}
