/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package bonsai.simulatorapi.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Defines values for EpisodeFinishTypesReason.
 */
public enum EpisodeFinishTypesReason {
    /** Enum value Invalid. */
    INVALID("Invalid"),

    /** Enum value Unspecified. */
    UNSPECIFIED("Unspecified"),

    /** Enum value LessonChanged. */
    LESSON_CHANGED("LessonChanged"),

    /** Enum value Terminal. */
    TERMINAL("Terminal"),

    /** Enum value Interrupted. */
    INTERRUPTED("Interrupted");

    /** The actual serialized value for a EpisodeFinishTypesReason instance. */
    private String value;

    EpisodeFinishTypesReason(String value) {
        this.value = value;
    }

    /**
     * Parses a serialized value to a EpisodeFinishTypesReason instance.
     *
     * @param value the serialized value to parse.
     * @return the parsed EpisodeFinishTypesReason object, or null if unable to parse.
     */
    @JsonCreator
    public static EpisodeFinishTypesReason fromString(String value) {
        EpisodeFinishTypesReason[] items = EpisodeFinishTypesReason.values();
        for (EpisodeFinishTypesReason item : items) {
            if (item.toString().equalsIgnoreCase(value)) {
                return item;
            }
        }
        return null;
    }

    @JsonValue
    @Override
    public String toString() {
        return this.value;
    }
}
