/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package bonsai.simulatorapi.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The Event model.
 */
public class Event {
    /**
     * Possible values include: 'Unspecified', 'EpisodeStart', 'EpisodeStep',
     * 'EpisodeFinish', 'PlaybackStart', 'PlaybackStep', 'PlaybackFinish',
     * 'Idle', 'Registered', 'Unregister'.
     */
    @JsonProperty(value = "type")
    private EventTypesEventType type;

    /**
     * The sessionId property.
     */
    @JsonProperty(value = "sessionId")
    private String sessionId;

    /**
     * The sequenceId property.
     */
    @JsonProperty(value = "sequenceId")
    private Integer sequenceId;

    /**
     * The episodeStart property.
     */
    @JsonProperty(value = "episodeStart")
    private EpisodeStart episodeStart;

    /**
     * The episodeStep property.
     */
    @JsonProperty(value = "episodeStep")
    private Step episodeStep;

    /**
     * The episodeFinish property.
     */
    @JsonProperty(value = "episodeFinish")
    private EpisodeFinish episodeFinish;

    /**
     * The playbackStart property.
     */
    @JsonProperty(value = "playbackStart")
    private Object playbackStart;

    /**
     * The playbackStep property.
     */
    @JsonProperty(value = "playbackStep")
    private Object playbackStep;

    /**
     * The playbackFinish property.
     */
    @JsonProperty(value = "playbackFinish")
    private Object playbackFinish;

    /**
     * The idle property.
     */
    @JsonProperty(value = "idle")
    private Idle idle;

    /**
     * The registered property.
     */
    @JsonProperty(value = "registered")
    private Object registered;

    /**
     * The unregister property.
     */
    @JsonProperty(value = "unregister")
    private Unregister unregister;

    /**
     * Possible values include: 'None', 'EpisodeStart', 'EpisodeStep',
     * 'EpisodeFinish', 'PlaybackStart', 'PlaybackStep', 'PlaybackFinish',
     * 'Idle', 'Registered', 'Unregister'.
     */
    @JsonProperty(value = "kindCase")
    private EventKindOneofCase kindCase;

    /**
     * Get possible values include: 'Unspecified', 'EpisodeStart', 'EpisodeStep', 'EpisodeFinish', 'PlaybackStart', 'PlaybackStep', 'PlaybackFinish', 'Idle', 'Registered', 'Unregister'.
     *
     * @return the type value
     */
    public EventTypesEventType type() {
        return this.type;
    }

    /**
     * Set possible values include: 'Unspecified', 'EpisodeStart', 'EpisodeStep', 'EpisodeFinish', 'PlaybackStart', 'PlaybackStep', 'PlaybackFinish', 'Idle', 'Registered', 'Unregister'.
     *
     * @param type the type value to set
     * @return the Event object itself.
     */
    public Event withType(EventTypesEventType type) {
        this.type = type;
        return this;
    }

    /**
     * Get the sessionId value.
     *
     * @return the sessionId value
     */
    public String sessionId() {
        return this.sessionId;
    }

    /**
     * Set the sessionId value.
     *
     * @param sessionId the sessionId value to set
     * @return the Event object itself.
     */
    public Event withSessionId(String sessionId) {
        this.sessionId = sessionId;
        return this;
    }

    /**
     * Get the sequenceId value.
     *
     * @return the sequenceId value
     */
    public Integer sequenceId() {
        return this.sequenceId;
    }

    /**
     * Set the sequenceId value.
     *
     * @param sequenceId the sequenceId value to set
     * @return the Event object itself.
     */
    public Event withSequenceId(Integer sequenceId) {
        this.sequenceId = sequenceId;
        return this;
    }

    /**
     * Get the episodeStart value.
     *
     * @return the episodeStart value
     */
    public EpisodeStart episodeStart() {
        return this.episodeStart;
    }

    /**
     * Set the episodeStart value.
     *
     * @param episodeStart the episodeStart value to set
     * @return the Event object itself.
     */
    public Event withEpisodeStart(EpisodeStart episodeStart) {
        this.episodeStart = episodeStart;
        return this;
    }

    /**
     * Get the episodeStep value.
     *
     * @return the episodeStep value
     */
    public Step episodeStep() {
        return this.episodeStep;
    }

    /**
     * Set the episodeStep value.
     *
     * @param episodeStep the episodeStep value to set
     * @return the Event object itself.
     */
    public Event withEpisodeStep(Step episodeStep) {
        this.episodeStep = episodeStep;
        return this;
    }

    /**
     * Get the episodeFinish value.
     *
     * @return the episodeFinish value
     */
    public EpisodeFinish episodeFinish() {
        return this.episodeFinish;
    }

    /**
     * Set the episodeFinish value.
     *
     * @param episodeFinish the episodeFinish value to set
     * @return the Event object itself.
     */
    public Event withEpisodeFinish(EpisodeFinish episodeFinish) {
        this.episodeFinish = episodeFinish;
        return this;
    }

    /**
     * Get the playbackStart value.
     *
     * @return the playbackStart value
     */
    public Object playbackStart() {
        return this.playbackStart;
    }

    /**
     * Set the playbackStart value.
     *
     * @param playbackStart the playbackStart value to set
     * @return the Event object itself.
     */
    public Event withPlaybackStart(Object playbackStart) {
        this.playbackStart = playbackStart;
        return this;
    }

    /**
     * Get the playbackStep value.
     *
     * @return the playbackStep value
     */
    public Object playbackStep() {
        return this.playbackStep;
    }

    /**
     * Set the playbackStep value.
     *
     * @param playbackStep the playbackStep value to set
     * @return the Event object itself.
     */
    public Event withPlaybackStep(Object playbackStep) {
        this.playbackStep = playbackStep;
        return this;
    }

    /**
     * Get the playbackFinish value.
     *
     * @return the playbackFinish value
     */
    public Object playbackFinish() {
        return this.playbackFinish;
    }

    /**
     * Set the playbackFinish value.
     *
     * @param playbackFinish the playbackFinish value to set
     * @return the Event object itself.
     */
    public Event withPlaybackFinish(Object playbackFinish) {
        this.playbackFinish = playbackFinish;
        return this;
    }

    /**
     * Get the idle value.
     *
     * @return the idle value
     */
    public Idle idle() {
        return this.idle;
    }

    /**
     * Set the idle value.
     *
     * @param idle the idle value to set
     * @return the Event object itself.
     */
    public Event withIdle(Idle idle) {
        this.idle = idle;
        return this;
    }

    /**
     * Get the registered value.
     *
     * @return the registered value
     */
    public Object registered() {
        return this.registered;
    }

    /**
     * Set the registered value.
     *
     * @param registered the registered value to set
     * @return the Event object itself.
     */
    public Event withRegistered(Object registered) {
        this.registered = registered;
        return this;
    }

    /**
     * Get the unregister value.
     *
     * @return the unregister value
     */
    public Unregister unregister() {
        return this.unregister;
    }

    /**
     * Set the unregister value.
     *
     * @param unregister the unregister value to set
     * @return the Event object itself.
     */
    public Event withUnregister(Unregister unregister) {
        this.unregister = unregister;
        return this;
    }

    /**
     * Get possible values include: 'None', 'EpisodeStart', 'EpisodeStep', 'EpisodeFinish', 'PlaybackStart', 'PlaybackStep', 'PlaybackFinish', 'Idle', 'Registered', 'Unregister'.
     *
     * @return the kindCase value
     */
    public EventKindOneofCase kindCase() {
        return this.kindCase;
    }

    /**
     * Set possible values include: 'None', 'EpisodeStart', 'EpisodeStep', 'EpisodeFinish', 'PlaybackStart', 'PlaybackStep', 'PlaybackFinish', 'Idle', 'Registered', 'Unregister'.
     *
     * @param kindCase the kindCase value to set
     * @return the Event object itself.
     */
    public Event withKindCase(EventKindOneofCase kindCase) {
        this.kindCase = kindCase;
        return this;
    }

}
