/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package bonsai.simulatorapi.models;

import org.joda.time.DateTime;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The SimulatorSessionMilestone model.
 */
public class SimulatorSessionMilestone {
    /**
     * The firstTime property.
     */
    @JsonProperty(value = "firstTime")
    private DateTime firstTime;

    /**
     * Get the firstTime value.
     *
     * @return the firstTime value
     */
    public DateTime firstTime() {
        return this.firstTime;
    }

    /**
     * Set the firstTime value.
     *
     * @param firstTime the firstTime value to set
     * @return the SimulatorSessionMilestone object itself.
     */
    public SimulatorSessionMilestone withFirstTime(DateTime firstTime) {
        this.firstTime = firstTime;
        return this;
    }

}
