/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package bonsai.simulatorapi.models;

import org.joda.time.DateTime;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The SimulatorSessionResponse model.
 */
public class SimulatorSessionResponse {
    /**
     * The sessionId property.
     */
    @JsonProperty(value = "sessionId", required = true)
    private String sessionId;

    /**
     * Possible values include: 'Deregistered', 'Attachable', 'Attached',
     * 'Detaching', 'Rejected'.
     */
    @JsonProperty(value = "sessionStatus")
    private SimulatorSessionTypesStatus sessionStatus;

    /**
     * The sessionProgress property.
     */
    @JsonProperty(value = "sessionProgress")
    private SimulatorSessionProgress sessionProgress;

    /**
     * The interfaceProperty property.
     */
    @JsonProperty(value = "interface")
    private SimulatorInterface interfaceProperty;

    /**
     * The simulatorContext property.
     */
    @JsonProperty(value = "simulatorContext")
    private SimulatorContext simulatorContext;

    /**
     * The registrationTime property.
     */
    @JsonProperty(value = "registrationTime", required = true)
    private DateTime registrationTime;

    /**
     * The lastSeenTime property.
     */
    @JsonProperty(value = "lastSeenTime", required = true)
    private DateTime lastSeenTime;

    /**
     * The iterationRate property.
     */
    @JsonProperty(value = "iterationRate")
    private Double iterationRate;

    /**
     * The details property.
     */
    @JsonProperty(value = "details")
    private String details;

    /**
     * Get the sessionId value.
     *
     * @return the sessionId value
     */
    public String sessionId() {
        return this.sessionId;
    }

    /**
     * Set the sessionId value.
     *
     * @param sessionId the sessionId value to set
     * @return the SimulatorSessionResponse object itself.
     */
    public SimulatorSessionResponse withSessionId(String sessionId) {
        this.sessionId = sessionId;
        return this;
    }

    /**
     * Get possible values include: 'Deregistered', 'Attachable', 'Attached', 'Detaching', 'Rejected'.
     *
     * @return the sessionStatus value
     */
    public SimulatorSessionTypesStatus sessionStatus() {
        return this.sessionStatus;
    }

    /**
     * Set possible values include: 'Deregistered', 'Attachable', 'Attached', 'Detaching', 'Rejected'.
     *
     * @param sessionStatus the sessionStatus value to set
     * @return the SimulatorSessionResponse object itself.
     */
    public SimulatorSessionResponse withSessionStatus(SimulatorSessionTypesStatus sessionStatus) {
        this.sessionStatus = sessionStatus;
        return this;
    }

    /**
     * Get the sessionProgress value.
     *
     * @return the sessionProgress value
     */
    public SimulatorSessionProgress sessionProgress() {
        return this.sessionProgress;
    }

    /**
     * Set the sessionProgress value.
     *
     * @param sessionProgress the sessionProgress value to set
     * @return the SimulatorSessionResponse object itself.
     */
    public SimulatorSessionResponse withSessionProgress(SimulatorSessionProgress sessionProgress) {
        this.sessionProgress = sessionProgress;
        return this;
    }

    /**
     * Get the interfaceProperty value.
     *
     * @return the interfaceProperty value
     */
    public SimulatorInterface interfaceProperty() {
        return this.interfaceProperty;
    }

    /**
     * Set the interfaceProperty value.
     *
     * @param interfaceProperty the interfaceProperty value to set
     * @return the SimulatorSessionResponse object itself.
     */
    public SimulatorSessionResponse withInterfaceProperty(SimulatorInterface interfaceProperty) {
        this.interfaceProperty = interfaceProperty;
        return this;
    }

    /**
     * Get the simulatorContext value.
     *
     * @return the simulatorContext value
     */
    public SimulatorContext simulatorContext() {
        return this.simulatorContext;
    }

    /**
     * Set the simulatorContext value.
     *
     * @param simulatorContext the simulatorContext value to set
     * @return the SimulatorSessionResponse object itself.
     */
    public SimulatorSessionResponse withSimulatorContext(SimulatorContext simulatorContext) {
        this.simulatorContext = simulatorContext;
        return this;
    }

    /**
     * Get the registrationTime value.
     *
     * @return the registrationTime value
     */
    public DateTime registrationTime() {
        return this.registrationTime;
    }

    /**
     * Set the registrationTime value.
     *
     * @param registrationTime the registrationTime value to set
     * @return the SimulatorSessionResponse object itself.
     */
    public SimulatorSessionResponse withRegistrationTime(DateTime registrationTime) {
        this.registrationTime = registrationTime;
        return this;
    }

    /**
     * Get the lastSeenTime value.
     *
     * @return the lastSeenTime value
     */
    public DateTime lastSeenTime() {
        return this.lastSeenTime;
    }

    /**
     * Set the lastSeenTime value.
     *
     * @param lastSeenTime the lastSeenTime value to set
     * @return the SimulatorSessionResponse object itself.
     */
    public SimulatorSessionResponse withLastSeenTime(DateTime lastSeenTime) {
        this.lastSeenTime = lastSeenTime;
        return this;
    }

    /**
     * Get the iterationRate value.
     *
     * @return the iterationRate value
     */
    public Double iterationRate() {
        return this.iterationRate;
    }

    /**
     * Set the iterationRate value.
     *
     * @param iterationRate the iterationRate value to set
     * @return the SimulatorSessionResponse object itself.
     */
    public SimulatorSessionResponse withIterationRate(Double iterationRate) {
        this.iterationRate = iterationRate;
        return this;
    }

    /**
     * Get the details value.
     *
     * @return the details value
     */
    public String details() {
        return this.details;
    }

    /**
     * Set the details value.
     *
     * @param details the details value to set
     * @return the SimulatorSessionResponse object itself.
     */
    public SimulatorSessionResponse withDetails(String details) {
        this.details = details;
        return this;
    }

}
