// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

/**
 * This package contains the implementation classes for SimulatorAPI.
 * This API allows simulators to provide states and receive commands from the platform.
 */
package microsoft.bonsai.simulatorapi.implementation;
