# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from enum import Enum


class SimulatorSessionTypesStatus(str, Enum):

    deregistered = "Deregistered"
    attachable = "Attachable"
    attached = "Attached"
    detaching = "Detaching"
    rejected = "Rejected"


class SimulatorContextTypesDeploymentMode(str, Enum):

    unspecified = "Unspecified"
    hosted = "Hosted"
    testing = "Testing"


class PurposeTypesAction(str, Enum):

    inactive = "Inactive"
    debug = "Debug"
    train = "Train"
    assess = "Assess"


class EventTypesEventType(str, Enum):

    unspecified = "Unspecified"
    episode_start = "EpisodeStart"
    episode_step = "EpisodeStep"
    episode_finish = "EpisodeFinish"
    playback_start = "PlaybackStart"
    playback_step = "PlaybackStep"
    playback_finish = "PlaybackFinish"
    idle = "Idle"
    registered = "Registered"
    unregister = "Unregister"


class EpisodeFinishTypesReason(str, Enum):

    invalid = "Invalid"
    unspecified = "Unspecified"
    lesson_changed = "LessonChanged"
    terminal = "Terminal"
    interrupted = "Interrupted"


class UnregisterTypesReason(str, Enum):

    unspecified = "Unspecified"
    finished = "Finished"
    error = "Error"
    not_found = "NotFound"


class EventKindOneofCase(str, Enum):

    none = "None"
    episode_start = "EpisodeStart"
    episode_step = "EpisodeStep"
    episode_finish = "EpisodeFinish"
    playback_start = "PlaybackStart"
    playback_step = "PlaybackStep"
    playback_finish = "PlaybackFinish"
    idle = "Idle"
    registered = "Registered"
    unregister = "Unregister"
