# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class SimulatorSessionProgress(Model):
    """SimulatorSessionProgress.

    :param attached:
    :type attached: ~bonsai.simulatorapi.models.SimulatorSessionMilestone
    :param iterated:
    :type iterated: ~bonsai.simulatorapi.models.SimulatorSessionMilestone
    """

    _attribute_map = {
        'attached': {'key': 'attached', 'type': 'SimulatorSessionMilestone'},
        'iterated': {'key': 'iterated', 'type': 'SimulatorSessionMilestone'},
    }

    def __init__(self, *, attached=None, iterated=None, **kwargs) -> None:
        super(SimulatorSessionProgress, self).__init__(**kwargs)
        self.attached = attached
        self.iterated = iterated
