# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class EpisodeStart(Model):
    """EpisodeStart.

    :param config:
    :type config: ~microsoft.bonsai.simulatorapi.models.Value
    """

    _attribute_map = {
        'config': {'key': 'config', 'type': 'Value'},
    }

    def __init__(self, **kwargs):
        super(EpisodeStart, self).__init__(**kwargs)
        self.config = kwargs.get('config', None)
