# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class Event(Model):
    """Event.

    All required parameters must be populated in order to send to Azure.

    :param type: Required.
    :type type: int
    :param session_id:
    :type session_id: str
    :param sequence_id: Required.
    :type sequence_id: int
    :param episode_start:
    :type episode_start: ~microsoft.bonsai.simulatorapi.models.EpisodeStart
    :param episode_step:
    :type episode_step: ~microsoft.bonsai.simulatorapi.models.Step
    :param episode_finish:
    :type episode_finish: ~microsoft.bonsai.simulatorapi.models.EpisodeFinish
    :param playback_start:
    :type playback_start: object
    :param playback_step:
    :type playback_step: object
    :param playback_finish:
    :type playback_finish: object
    :param idle:
    :type idle: ~microsoft.bonsai.simulatorapi.models.Idle
    :param registered:
    :type registered: object
    :param unregister:
    :type unregister: ~microsoft.bonsai.simulatorapi.models.Unregister
    :param kind_case: Required.
    :type kind_case: int
    """

    _validation = {
        'type': {'required': True},
        'sequence_id': {'required': True},
        'kind_case': {'required': True},
    }

    _attribute_map = {
        'type': {'key': 'type', 'type': 'int'},
        'session_id': {'key': 'sessionId', 'type': 'str'},
        'sequence_id': {'key': 'sequenceId', 'type': 'int'},
        'episode_start': {'key': 'episodeStart', 'type': 'EpisodeStart'},
        'episode_step': {'key': 'episodeStep', 'type': 'Step'},
        'episode_finish': {'key': 'episodeFinish', 'type': 'EpisodeFinish'},
        'playback_start': {'key': 'playbackStart', 'type': 'object'},
        'playback_step': {'key': 'playbackStep', 'type': 'object'},
        'playback_finish': {'key': 'playbackFinish', 'type': 'object'},
        'idle': {'key': 'idle', 'type': 'Idle'},
        'registered': {'key': 'registered', 'type': 'object'},
        'unregister': {'key': 'unregister', 'type': 'Unregister'},
        'kind_case': {'key': 'kindCase', 'type': 'int'},
    }

    def __init__(self, **kwargs):
        super(Event, self).__init__(**kwargs)
        self.type = kwargs.get('type', None)
        self.session_id = kwargs.get('session_id', None)
        self.sequence_id = kwargs.get('sequence_id', None)
        self.episode_start = kwargs.get('episode_start', None)
        self.episode_step = kwargs.get('episode_step', None)
        self.episode_finish = kwargs.get('episode_finish', None)
        self.playback_start = kwargs.get('playback_start', None)
        self.playback_step = kwargs.get('playback_step', None)
        self.playback_finish = kwargs.get('playback_finish', None)
        self.idle = kwargs.get('idle', None)
        self.registered = kwargs.get('registered', None)
        self.unregister = kwargs.get('unregister', None)
        self.kind_case = kwargs.get('kind_case', None)
