# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class PurposeTarget(Model):
    """PurposeTarget.

    All required parameters must be populated in order to send to Azure.

    :param workspace_name:
    :type workspace_name: str
    :param brain_name:
    :type brain_name: str
    :param brain_version: Required.
    :type brain_version: int
    :param concept_name:
    :type concept_name: str
    """

    _validation = {
        'brain_version': {'required': True},
    }

    _attribute_map = {
        'workspace_name': {'key': 'workspaceName', 'type': 'str'},
        'brain_name': {'key': 'brainName', 'type': 'str'},
        'brain_version': {'key': 'brainVersion', 'type': 'int'},
        'concept_name': {'key': 'conceptName', 'type': 'str'},
    }

    def __init__(self, *, brain_version: int, workspace_name: str=None, brain_name: str=None, concept_name: str=None, **kwargs) -> None:
        super(PurposeTarget, self).__init__(**kwargs)
        self.workspace_name = workspace_name
        self.brain_name = brain_name
        self.brain_version = brain_version
        self.concept_name = concept_name
