# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class SimulatorSessionSummary(Model):
    """SimulatorSessionSummary.

    All required parameters must be populated in order to send to Azure.

    :param session_id:
    :type session_id: str
    :param session_status: Required.
    :type session_status: int
    :param simulator_name:
    :type simulator_name: str
    :param simulator_context:
    :type simulator_context:
     ~microsoft.bonsai.simulatorapi.models.SimulatorContext
    """

    _validation = {
        'session_status': {'required': True},
    }

    _attribute_map = {
        'session_id': {'key': 'sessionId', 'type': 'str'},
        'session_status': {'key': 'sessionStatus', 'type': 'int'},
        'simulator_name': {'key': 'simulatorName', 'type': 'str'},
        'simulator_context': {'key': 'simulatorContext', 'type': 'SimulatorContext'},
    }

    def __init__(self, **kwargs):
        super(SimulatorSessionSummary, self).__init__(**kwargs)
        self.session_id = kwargs.get('session_id', None)
        self.session_status = kwargs.get('session_status', None)
        self.simulator_name = kwargs.get('simulator_name', None)
        self.simulator_context = kwargs.get('simulator_context', None)
