# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class SimulatorSession(Model):
    """SimulatorSession.

    All required parameters must be populated in order to send to Azure.

    :param session_id:
    :type session_id: str
    :param session_status: Required.
    :type session_status: int
    :param session_progress:
    :type session_progress:
     ~microsoft.bonsai.simulatorapi.models.SimulatorSessionProgress
    :param interface:
    :type interface: ~microsoft.bonsai.simulatorapi.models.SimulatorInterface
    :param simulator_context:
    :type simulator_context:
     ~microsoft.bonsai.simulatorapi.models.SimulatorContext
    :param registration_time:
    :type registration_time: ~microsoft.bonsai.simulatorapi.models.Timestamp
    :param last_seen_time:
    :type last_seen_time: ~microsoft.bonsai.simulatorapi.models.Timestamp
    :param iteration_rate: Required.
    :type iteration_rate: float
    :param details:
    :type details: str
    """

    _validation = {
        'session_status': {'required': True},
        'iteration_rate': {'required': True},
    }

    _attribute_map = {
        'session_id': {'key': 'sessionId', 'type': 'str'},
        'session_status': {'key': 'sessionStatus', 'type': 'int'},
        'session_progress': {'key': 'sessionProgress', 'type': 'SimulatorSessionProgress'},
        'interface': {'key': 'interface', 'type': 'SimulatorInterface'},
        'simulator_context': {'key': 'simulatorContext', 'type': 'SimulatorContext'},
        'registration_time': {'key': 'registrationTime', 'type': 'Timestamp'},
        'last_seen_time': {'key': 'lastSeenTime', 'type': 'Timestamp'},
        'iteration_rate': {'key': 'iterationRate', 'type': 'float'},
        'details': {'key': 'details', 'type': 'str'},
    }

    def __init__(self, *, session_status: int, iteration_rate: float, session_id: str=None, session_progress=None, interface=None, simulator_context=None, registration_time=None, last_seen_time=None, details: str=None, **kwargs) -> None:
        super(SimulatorSession, self).__init__(**kwargs)
        self.session_id = session_id
        self.session_status = session_status
        self.session_progress = session_progress
        self.interface = interface
        self.simulator_context = simulator_context
        self.registration_time = registration_time
        self.last_seen_time = last_seen_time
        self.iteration_rate = iteration_rate
        self.details = details
