# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class SimulatorContext(Model):
    """SimulatorContext.

    All required parameters must be populated in order to send to Azure.

    :param deployment_mode: Required.
    :type deployment_mode: int
    :param deployment_details:
    :type deployment_details: str
    :param simulator_client_id:
    :type simulator_client_id: str
    :param collection:
    :type collection: str
    :param package:
    :type package: str
    :param purpose:
    :type purpose: ~microsoft.bonsai.simulatorapi.models.Purpose
    """

    _validation = {
        'deployment_mode': {'required': True},
    }

    _attribute_map = {
        'deployment_mode': {'key': 'deploymentMode', 'type': 'int'},
        'deployment_details': {'key': 'deploymentDetails', 'type': 'str'},
        'simulator_client_id': {'key': 'simulatorClientId', 'type': 'str'},
        'collection': {'key': 'collection', 'type': 'str'},
        'package': {'key': 'package', 'type': 'str'},
        'purpose': {'key': 'purpose', 'type': 'Purpose'},
    }

    def __init__(self, **kwargs):
        super(SimulatorContext, self).__init__(**kwargs)
        self.deployment_mode = kwargs.get('deployment_mode', None)
        self.deployment_details = kwargs.get('deployment_details', None)
        self.simulator_client_id = kwargs.get('simulator_client_id', None)
        self.collection = kwargs.get('collection', None)
        self.package = kwargs.get('package', None)
        self.purpose = kwargs.get('purpose', None)
