# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class SimulatorInfo(Model):
    """SimulatorInfo.

    All required parameters must be populated in order to send to Azure.

    :param interface:
    :type interface: ~microsoft.bonsai.simulatorapi.models.SimulatorInterface
    :param simulator_context:
    :type simulator_context:
     ~microsoft.bonsai.simulatorapi.models.SimulatorContext
    :param last_seen:
    :type last_seen: ~microsoft.bonsai.simulatorapi.models.Timestamp
    :param registration_time:
    :type registration_time: ~microsoft.bonsai.simulatorapi.models.Timestamp
    :param details:
    :type details: str
    :param iteration_rate: Required.
    :type iteration_rate: float
    :param session_status: Required.
    :type session_status: int
    """

    _validation = {
        'iteration_rate': {'required': True},
        'session_status': {'required': True},
    }

    _attribute_map = {
        'interface': {'key': 'interface', 'type': 'SimulatorInterface'},
        'simulator_context': {'key': 'simulatorContext', 'type': 'SimulatorContext'},
        'last_seen': {'key': 'lastSeen', 'type': 'Timestamp'},
        'registration_time': {'key': 'registrationTime', 'type': 'Timestamp'},
        'details': {'key': 'details', 'type': 'str'},
        'iteration_rate': {'key': 'iterationRate', 'type': 'float'},
        'session_status': {'key': 'sessionStatus', 'type': 'int'},
    }

    def __init__(self, **kwargs):
        super(SimulatorInfo, self).__init__(**kwargs)
        self.interface = kwargs.get('interface', None)
        self.simulator_context = kwargs.get('simulator_context', None)
        self.last_seen = kwargs.get('last_seen', None)
        self.registration_time = kwargs.get('registration_time', None)
        self.details = kwargs.get('details', None)
        self.iteration_rate = kwargs.get('iteration_rate', None)
        self.session_status = kwargs.get('session_status', None)
