# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class Step(Model):
    """Step.

    :param action:
    :type action: ~microsoft.bonsai.simulatorapi.models.Value
    """

    _attribute_map = {
        'action': {'key': 'action', 'type': 'Value'},
    }

    def __init__(self, **kwargs):
        super(Step, self).__init__(**kwargs)
        self.action = kwargs.get('action', None)
