# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class Value(Model):
    """Value.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    All required parameters must be populated in order to send to Azure.

    :ivar null_value: Required.  Default value: 0 .
    :vartype null_value: int
    :param number_value: Required.
    :type number_value: float
    :param string_value:
    :type string_value: str
    :param bool_value: Required.
    :type bool_value: bool
    :param struct_value:
    :type struct_value: dict[str, object]
    :param list_value:
    :type list_value: ~microsoft.bonsai.simulatorapi.models.ListValue
    :param kind_case: Required.
    :type kind_case: int
    """

    _validation = {
        'null_value': {'required': True, 'constant': True},
        'number_value': {'required': True},
        'bool_value': {'required': True},
        'kind_case': {'required': True},
    }

    _attribute_map = {
        'null_value': {'key': 'nullValue', 'type': 'int'},
        'number_value': {'key': 'numberValue', 'type': 'float'},
        'string_value': {'key': 'stringValue', 'type': 'str'},
        'bool_value': {'key': 'boolValue', 'type': 'bool'},
        'struct_value': {'key': 'structValue', 'type': '{object}'},
        'list_value': {'key': 'listValue', 'type': 'ListValue'},
        'kind_case': {'key': 'kindCase', 'type': 'int'},
    }

    null_value = 0

    def __init__(self, **kwargs):
        super(Value, self).__init__(**kwargs)
        self.number_value = kwargs.get('number_value', None)
        self.string_value = kwargs.get('string_value', None)
        self.bool_value = kwargs.get('bool_value', None)
        self.struct_value = kwargs.get('struct_value', None)
        self.list_value = kwargs.get('list_value', None)
        self.kind_case = kwargs.get('kind_case', None)
