# Note that a Python 3.9 base image is used because the official Python docker images at
# https://hub.docker.com/_/python no longer support Python 3.7 for Windows Server Core.
FROM python:3.9.10-windowsservercore-1809

# $ProgressPreference: https://github.com/PowerShell/PowerShell/issues/2138#issuecomment-251261324
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

WORKDIR /src
COPY . /src
ADD requirements.txt /src/requirements.txt

RUN pip install --upgrade pip --user
RUN pip3 install setuptools wheel 
RUN pip3 install -r requirements.txt 
# update certificates:
RUN certutil -generateSSTFromWU roots.sst 
RUN certutil -addstore -f root roots.sst 
RUN del roots.sst

CMD "python main.py"