FROM python:3.7.3-windowsservercore-1809

# $ProgressPreference: https://github.com/PowerShell/PowerShell/issues/2138#issuecomment-251261324
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

WORKDIR /src
COPY . /src
ADD requirements.txt /src/requirements.txt

RUN pip3 install setuptools wheel 
RUN pip3 install -r requirements.txt 
# update certificates:
RUN certutil -generateSSTFromWU roots.sst 
RUN certutil -addstore -f root roots.sst 
RUN del roots.sst

CMD "python main.py"